# site settings
title: CeS3
subtitle: 
email: 1540962271@qq.com
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "" # the subpath of your site, e.g. /blog
url: https://ces-3.github.io/ # the base hostname & protocol for your site
author: CeS3
street_address:
city:
state:
zip_code:
country: China
phone: (86)18650520938

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/CeS-3/
  GitLab:
  Google-Plus:
  Instagram:
  LinkedIn:
  Twitter:
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
